# Generated by Django 5.1.5 on 2025-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('short_name', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('idx_number', models.CharField(max_length=128)),
                ('contact_first_name', models.CharField(max_length=16)),
                ('contact_last_name', models.CharField(max_length=16)),
                ('contact_middle_name', models.CharField(max_length=16)),
                ('ceo_first_name', models.CharField(max_length=16)),
                ('ceo_last_name', models.CharField(max_length=16)),
                ('ceo_middle_name', models.CharField(max_length=16)),
                ('activity', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('contact_phone', models.CharField(max_length=16)),
            ],
        ),
    ]
