# Generated by Django 5.1.5 on 2025-02-12 13:40

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='organizations',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='status',
            field=models.CharField(default='new', max_length=16),
        ),
        migrations.AddIndex(
            model_name='organizations',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='organizatio_search__d804ba_gin'),
        ),
    ]
