# Generated by Django 5.1.5 on 2025-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizations_comment_organizations_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='short_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
