# Generated by Django 5.1.5 on 2025-02-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizations_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=16),
        ),
    ]
